---
title: "Working with simple feature and bounding box objects"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Working with simple feature and bounding box objects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sfext)
library(ggplot2)
```


```{r}
theme_set(theme_void())

nc <- read_sf_path(system.file("shape/nc.shp", package = "sf"))
nc <- st_transform_ext(nc, crs = 3857)
```


```{r}
# Get a bbox for a 1/4 mile square around Ashe County
bbox_large <-
  st_bbox_ext(
    x = nc[1,],
    dist = 1 / 8,
    unit = "mile"
  )

# Check if it is a bbox
is_bbox(bbox_large)

large_sf <- as_sf(bbox_large)

# Checks if data is a sf object
is_sf(large_sf)

# Checks if data is a sf, bbox, or sfc object
is_sf(large_sf, ext = TRUE)

# Check if data is sfc
is_sfc(large_sf$geometry)

# Check if data is a named list of sf objects
is_sf_list(list("large_sf" = large_sf))

# Check if two sf objects have the same coordinate reference system
is_same_crs(large_sf, bbox_large)

# Additional checks include is_raster() is_sp()
```


```{r}
bbox_small <-
  st_bbox_ext(
    x = bbox_large,
    dist = - 1 / 16,
    unit = "mile"
  )

small_sf <- as_sf(bbox_small)

basemap <-
  ggplot2::ggplot() +
  geom_sf(
    data = large_sf,
    fill = "darkgreen",
    alpha = 0.5
  ) +
  geom_sf(
    data = small_sf,
    fill = "lightgreen",
    alpha = 0.5
  )

basemap
```


```{r}
small_diamond_sf <-
  st_inscribed_square(x = bbox_small, rotate = 45)

large_diamond_sf <-
  st_scale_rotate(x = bbox_large, scale = 1.25, rotate = 15)

basemap +
  geom_sf(
    data = small_diamond_sf,
    fill = NA,
    color = "black",
    alpha = 0.1
  ) +
  geom_sf(
    data = large_diamond_sf,
    fill = NA,
    color = "black",
    alpha = 0.1
  )
```

```{r}
center <-
  st_center(x = bbox_large)

dplyr::glimpse(center)
```


```{r}
bbox_stretched <-
  sf_bbox_expand(
    bbox = bbox_small,
    y_nudge = 50
  )

basemap +
  geom_sf(
    data = as_sf(bbox_stretched),
    alpha = 0.1
  )

paper_sf <-
  st_bbox_asp(
    x = bbox_large,
    asp = 8.5 / 11,
    class = "sf"
  )

basemap +
  geom_sf(
    data = paper_sf,
    alpha = 0.1,
    fill = "yellow",
    linetype = "dashed"
  )
```
