# generated by {burglr}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_yesno (copied from cliExtras:::cli_yesno)
# from cliExtras 0.1.0
`cli_yesno` <- function(message, yes = c(
                          "Yes", "Definitely", "For sure", "Yup",
                          "Yeah", "I agree", "Absolutely"
                        ), no = c(
                          "No way", "Not now",
                          "Negative", "No", "Nope", "Absolutely not"
                        ), n_yes = 1, n_no = 1,
                        call = .envir, .envir = parent.frame()) {
  cli_abort_ifnot(c(
    "User input required, but session is not interactive.",
    "Query: ", message
  ), call = .envir, condition = is_interactive())
  qs <- c(sample(yes, n_yes), sample(no, n_no))
  rand <- sample(length(qs))
  cli_inform(message, .envir = .envir)
  utils::menu(qs[rand]) == which(rand == 1)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_abort_ifnot (copied from cliExtras:::cli_abort_ifnot)
# from cliExtras 0.1.0
`cli_abort_ifnot` <- function(..., condition = FALSE, .data = NULL, call = .envir,
                              .envir = parent.frame()) {
  if (!rlang::is_logical(condition)) {
    condition <- condition_as_fn(condition, .data, call = call)
  }
  if (!condition) {
    cli_abort(..., call = call, .envir = .envir)
  }
  invisible(NULL)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_warn_ifnot (copied from cliExtras:::cli_warn_ifnot)
# from cliExtras 0.1.0
`cli_warn_ifnot` <- function(..., condition = FALSE, .data = NULL, .envir = parent.frame()) {
  if (!rlang::is_logical(condition)) {
    condition <- condition_as_fn(condition, .data, call = call)
  }
  if (!condition) {
    cli_warn(..., .envir = .envir)
  }
  invisible(NULL)
}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# cli_ask (copied from cliExtras:::cli_ask)
# from cliExtras 0.1.0
`cli_ask` <- function(message, ..., prompt = ">> ", .envir = parent.frame()) {
  cli_inform(c(`>` = message, ...), .envir = .envir)
  readline(prompt = prompt)
}
