# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:isstatic
# ======================================================================

#' Does string contain the specified file type or any file extension?
#'
#' Check if string contains any filetype or the provided filetype. If string is
#' `NULL`, returns `FALSE`.
#'
#' @param string String to be tested with or without filetype. Defaults to
#'   `NULL`.
#' @param fileext File type to test against. Optional.
#' @param ignore.case If `FALSE`, the pattern matching is case sensitive. If
#'   `TRUE`, case is ignored.
#' @noRd
has_fileext <- function(string = NULL, fileext = NULL, ignore.case = FALSE) {
  if (is.null(string)) {
    return(FALSE)
  }

  if (is.null(fileext)) {
    fileext <- "[a-zA-Z0-9]+"
  }

  is_fileext_path(string, fileext, ignore.case)
}

#' Do two object have an identical length?
#'
#' @param x,y Two strings or character vectors to compare.
#' @param ... Additional parameters passed to [identical()]
#' @noRd
has_same_len <- function(x, y, ...) {
  identical(length(x), length(y), ...)
}

#' Do all items in a list or vector return TRUE from a predicate function?
#'
#' @param x A list or vector passed to [vapply()].
#' @param FUN Function passed to FUN parameter of [vapply()].
#' @noRd
is_all <- function(x, FUN, ...) {
  all(vapply(x, FUN, FUN.VALUE = TRUE, ...))
}

#' Do any items in a list or vector return TRUE from a predicate function?
#'
#' @param x A list or vector passed to [vapply()].
#' @param FUN Function passed to FUN parameter of [vapply()].
#' @noRd
is_any <- function(x, FUN, ...) {
  any(vapply(x, FUN, FUN.VALUE = TRUE, ...))
}

#' Are any of x in y?
#'
#' @param x Object to be tested.
#' @param y Vector to compare x to.
#' @noRd
is_any_in <- function(x, y) {
  any(x %in% y)
}

#' Is this a CSV file path or url?
#'
#' @noRd
is_csv_path <- function(x, ignore.case = TRUE) {
  is_fileext_path(x, "csv", ignore.case)
}

#' Is a character vector an ArcGIS MapServer or FeatureServer URL?
#'
#' @param x Object to be tested.
#' @noRd
is_esri_url <- function(x) {
  grepl("/MapServer|/FeatureServer", x)
}

#' Is this a Excel file path or url?
#'
#' @noRd
is_excel_path <- function(x, ignore.case = TRUE) {
  is_fileext_path(x, c("xls", "xlsx"), ignore.case)
}

#' Is this a file path or url ending in the specified file extension?
#'
#' @noRd
is_fileext_path <- function(x, fileext, ignore.case = TRUE) {
  grepl(
    paste0("\\.", paste0(fileext, collapse = "|"), "$(?!\\.)"),
    x,
    ignore.case = ignore.case, perl = TRUE
  )
}

#' Is this a GeoJSON file path or url?
#'
#' @noRd
is_geojson_path <- function(x, ignore.case = TRUE) {
  is_fileext_path(x, "geojson", ignore.case)
}

#' Is a character vector a URL for a GitHub Gist?
#'
#' @param x Object to be tested.
#' @noRd
is_gist_url <- function(x) {
  grepl("^https://gist.github.com/", x)
}

#' Is a character vector a Google Maps URL?
#'
#' @param x Object to be tested.
#' @noRd
is_gmap_url <- function(x) {
  grepl("^https://www.google.com/maps/", x)
}

#' Is a character vector a Google Sheets URL?
#'
#' @param x Object to be tested.
#' @noRd
is_gsheet_url <- function(x) {
  grepl("^https://docs.google.com/spreadsheets/", x)
}

#' Is this a RDA file path or url?
#'
#' @noRd
is_rda_path <- function(x, ignore.case = TRUE) {
  is_fileext_path(x, "rda", ignore.case)
}

#' Is this a RDS, RDA, or RData file path or url?
#'
#' @noRd
is_rdata_path <- function(x, ignore.case = TRUE) {
  any(
    c(
      is_rda_path(x, ignore.case),
      is_rds_path(x, ignore.case),
      is_fileext_path(x, "RData", ignore.case)
    )
  )
}

#' Is this a RDS file path or url?
#'
#' @noRd
is_rds_path <- function(x, ignore.case = TRUE) {
  is_fileext_path(x, "rds", ignore.case)
}

#' Is this a unit class object?
#'
#' @param x Object to be tested.
#' @noRd
is_unit <- function(x) {
  inherits(x, c("unit", "unit_v2"))
}

#' Is this a units class object?
#'
#' @param x Object to be tested.
#' @noRd
is_units <- function(x) {
  inherits(x, "units")
}

#' Is a character vector a URL?
#'
#' @param x Object to be tested.
#' @noRd
is_url <- function(x) {
  grepl(
    "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+",
    x
  )
}
# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:stringstatic
# ======================================================================

#' Detect the presence or absence of a pattern in a string
#'
#' Dependency-free drop-in alternative for `stringr::str_detect()`.
#'
#' @source Adapted from the [stringr](https://stringr.tidyverse.org/) package.
#'
#' @param string Input vector.
#'   Either a character vector, or something coercible to one.
#'
#' @param pattern Pattern to look for.
#'
#'   The default interpretation is a regular expression,
#'   as described in [base::regex].
#'   Control options with [regex()].
#'
#'   Match a fixed string (i.e. by comparing only bytes), using [fixed()].
#'   This is fast, but approximate.
#'
#' @param negate If `TRUE`, return non-matching elements.
#'
#' @return A logical vector.
#' @noRd
str_detect <- function(string, pattern, negate = FALSE) {
  is_fixed <- inherits(pattern, "fixed")
  ignore.case <- isTRUE(attr(pattern, "options")$case_insensitive)

  if (length(string) == 0 || length(pattern) == 0) {
    return(logical(0))
  }

  indices <- Vectorize(grep, c("pattern", "x"), USE.NAMES = FALSE)(
    pattern,
    x = string,
    ignore.case = ignore.case,
    perl = !is_fixed,
    fixed = is_fixed,
    invert = negate
  )

  result <- as.logical(lengths(indices))
  result[is.na(string)] <- NA
  result
}

#' Extract matching patterns from a string
#'
#' Dependency-free drop-in alternative for `stringr::str_extract()`.
#'
#' @source Adapted from the [stringr](https://stringr.tidyverse.org/) package.
#'
#' @param string Input vector.
#'   Either a character vector, or something coercible to one.
#'
#' @param pattern Pattern to look for.
#'
#'   The default interpretation is a regular expression,
#'   as described in [base::regex].
#'   Control options with [regex()].
#'
#'   Match a fixed string (i.e. by comparing only bytes), using [fixed()].
#'   This is fast, but approximate.
#'
#' @return A character matrix.
#'   The first column is the complete match,
#'   followed by one column for each capture group.
#' @noRd
str_extract <- function(string, pattern) {
  ignore.case <- isTRUE(attr(pattern, "options")$case_insensitive)
  is_fixed <- !ignore.case && inherits(pattern, "fixed")

  if (length(string) == 0 || length(pattern) == 0) {
    return(character(0))
  }

  result <- Map(
    function(string, pattern) {
      if (is.na(string) || is.na(pattern)) {
        return(NA_character_)
      }

      regmatches(
        x = string,
        m = regexpr(
          pattern = pattern,
          text = string,
          ignore.case = ignore.case,
          perl = !is_fixed,
          fixed = is_fixed
        )
      )
    },
    string, pattern,
    USE.NAMES = FALSE
  )

  result[lengths(result) == 0] <- NA_character_
  unlist(result)
}

#' Remove matched patterns in a string
#'
#' Dependency-free drop-in alternative for `stringr::str_remove()`.
#'
#' @source Adapted from the [stringr](https://stringr.tidyverse.org/) package.
#'
#' @param string Input vector.
#'   Either a character vector, or something coercible to one.
#'
#' @param pattern Pattern to look for.
#'
#'   The default interpretation is a regular expression,
#'   as described in [base::regex].
#'   Control options with [regex()].
#'
#'   Match a fixed string (i.e. by comparing only bytes), using [fixed()].
#'   This is fast, but approximate.
#'
#' @return A character vector.
#' @noRd
str_remove <- function(string, pattern) {
  ignore.case <- isTRUE(attr(pattern, "options")$case_insensitive)
  is_fixed <- !ignore.case && inherits(pattern, "fixed")

  sub <- Vectorize(sub, c("pattern", "x"), USE.NAMES = FALSE)

  sub(
    pattern,
    replacement = "",
    x = string,
    ignore.case = ignore.case,
    perl = !is_fixed,
    fixed = is_fixed
  )
}

#' Replace matched patterns in a string
#'
#' Dependency-free drop-in alternative for `stringr::str_replace()`.
#'
#' @source Adapted from the [stringr](https://stringr.tidyverse.org/) package.
#'
#' @param string Input vector.
#'   Either a character vector, or something coercible to one.
#'
#' @param pattern Pattern to look for.
#'
#'   The default interpretation is a regular expression,
#'   as described in [base::regex].
#'   Control options with [regex()].
#'
#'   Match a fixed string (i.e. by comparing only bytes), using [fixed()].
#'   This is fast, but approximate.
#'
#' @param replacement A character vector of replacements.
#'   Should be either length one, or the same length as `string` or `pattern`.
#'   References of the form `\1`, `\2`, etc. will be replaced with the contents
#'   of the respective matched group (created by `()`).
#'
#'   To replace the complete string with `NA`,
#'   use `replacement = NA_character_`.
#'
#'   Using a function for `replacement` is not yet supported.
#'
#' @return A character vector.
#' @noRd
str_replace <- function(string, pattern, replacement) {
  ignore.case <- isTRUE(attr(pattern, "options")$case_insensitive)
  is_fixed <- !ignore.case && inherits(pattern, "fixed")

  sub <- Vectorize(sub, c("pattern", "replacement", "x"), USE.NAMES = FALSE)

  sub(
    pattern,
    replacement,
    x = string,
    ignore.case = ignore.case,
    perl = !is_fixed,
    fixed = is_fixed
  )
}
